-- Supabase schema for the Next.js portfolio.
-- Run this once in Supabase Dashboard > SQL Editor.
-- The public site and dashboard access these tables directly through Supabase.

create extension if not exists "pgcrypto";

create table if not exists public.personals (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    title varchar(255) not null,
    university varchar(255) not null,
    faculty varchar(255) not null,
    bio text not null,
    tagline varchar(255) not null,
    photo varchar(255),
    location varchar(255) not null,
    quote varchar(255) not null,
    cv_file varchar(255),
    status varchar(255) not null default 'Open to Work',
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);

create table if not exists public.skills (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    category varchar(255) not null,
    icon varchar(255),
    proficiency integer,
    sort_order integer not null default 0,
    is_visible boolean not null default true,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);

create table if not exists public.journeys (
    id bigint generated by default as identity primary key,
    year varchar(255) not null,
    title varchar(255) not null,
    description text not null,
    type varchar(255) not null default 'education',
    institution varchar(255),
    image varchar(255),
    sort_order integer not null default 0,
    is_visible boolean not null default true,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);

create table if not exists public.projects (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    category varchar(255) not null,
    description text not null,
    thumbnail varchar(255),
    demo_url varchar(255),
    repo_url varchar(255),
    year smallint,
    is_featured boolean not null default false,
    is_visible boolean not null default true,
    sort_order integer not null default 0,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);

create table if not exists public.project_tags (
    id bigint generated by default as identity primary key,
    project_id bigint not null references public.projects(id) on delete cascade,
    tag varchar(255) not null,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);

create table if not exists public.certificates (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    issuer varchar(255) not null,
    credential_id varchar(255),
    credential_url varchar(255),
    image varchar(255),
    year smallint not null,
    is_visible boolean not null default true,
    sort_order integer not null default 0,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);

create table if not exists public.experiences (
    id bigint generated by default as identity primary key,
    company varchar(255) not null,
    position varchar(255) not null,
    category varchar(32) not null default 'work',
    type varchar(255) not null default 'internship',
    start_date date,
    end_date date,
    is_current boolean not null default false,
    description text not null,
    location varchar(255),
    is_visible boolean not null default true,
    sort_order integer not null default 0,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);

create table if not exists public.contacts (
    id bigint generated by default as identity primary key,
    platform varchar(255) not null,
    label varchar(255) not null,
    value varchar(255) not null,
    icon varchar(255),
    is_visible boolean not null default true,
    sort_order integer not null default 0,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);

create index if not exists projects_visible_order_idx on public.projects (is_visible, sort_order);
create index if not exists project_tags_project_id_idx on public.project_tags (project_id);
create index if not exists skills_visible_order_idx on public.skills (is_visible, sort_order);
create index if not exists journeys_visible_order_idx on public.journeys (is_visible, sort_order);
create index if not exists certificates_visible_order_idx on public.certificates (is_visible, sort_order);
create index if not exists experiences_visible_order_idx on public.experiences (is_visible, sort_order);
create index if not exists contacts_visible_order_idx on public.contacts (is_visible, sort_order);

-- Public read policies are safe for the portfolio's published content.
alter table public.personals enable row level security;
alter table public.skills enable row level security;
alter table public.journeys enable row level security;
alter table public.projects enable row level security;
alter table public.project_tags enable row level security;
alter table public.certificates enable row level security;
alter table public.experiences enable row level security;
alter table public.contacts enable row level security;

drop policy if exists "public can read personals" on public.personals;
create policy "public can read personals" on public.personals for select to anon, authenticated using (true);

drop policy if exists "public can read visible skills" on public.skills;
create policy "public can read visible skills" on public.skills for select to anon, authenticated using (is_visible = true);

drop policy if exists "public can read visible journeys" on public.journeys;
create policy "public can read visible journeys" on public.journeys for select to anon, authenticated using (is_visible = true);

drop policy if exists "public can read visible projects" on public.projects;
create policy "public can read visible projects" on public.projects for select to anon, authenticated using (is_visible = true);

drop policy if exists "public can read tags for visible projects" on public.project_tags;
create policy "public can read tags for visible projects" on public.project_tags for select to anon, authenticated
using (exists (select 1 from public.projects p where p.id = project_tags.project_id and p.is_visible = true));

drop policy if exists "public can read visible certificates" on public.certificates;
create policy "public can read visible certificates" on public.certificates for select to anon, authenticated using (is_visible = true);

drop policy if exists "public can read visible experiences" on public.experiences;
create policy "public can read visible experiences" on public.experiences for select to anon, authenticated using (is_visible = true);

drop policy if exists "public can read visible contacts" on public.contacts;
create policy "public can read visible contacts" on public.contacts for select to anon, authenticated using (is_visible = true);

-- Optional starter content. Delete this section if you want an empty dashboard.
insert into public.personals
    (name, title, university, faculty, bio, tagline, location, quote, status, created_at, updated_at)
select
    'Djibril Rangga Deja',
    'AI Engineer · n8n Automation',
    'Universitas Brawijaya',
    'Fakultas Vokasi',
    'AI Engineer yang merancang agent, workflow n8n, dan automasi yang membantu tim bekerja lebih cepat tanpa kehilangan kontrol.',
    'AI Engineer · n8n Automation',
    'Malang, Jawa Timur',
    'Bangun sistem yang membantu manusia bekerja lebih baik.',
    'Open to Work',
    now(), now()
where not exists (select 1 from public.personals);

-- Repair the legacy double-encoded middle dot in existing starter records.
update public.personals
set
    title = replace(title, chr(194) || chr(183), '-'),
    tagline = replace(tagline, chr(194) || chr(183), '-')
where title like '%' || chr(194) || chr(183) || '%'
   or tagline like '%' || chr(194) || chr(183) || '%';

insert into public.skills (name, category, sort_order)
select * from (values
    ('n8n', 'tech', 0), ('AI Agents', 'tech', 1), ('Supabase', 'tech', 2),
    ('Laravel', 'tech', 3), ('React', 'tech', 4), ('API Design', 'hard', 5)
) as seed(name, category, sort_order)
where not exists (select 1 from public.skills);

insert into public.projects
    (title, category, description, year, is_featured, is_visible, sort_order)
select * from (values
    ('AI Ops Workflow', 'automation', 'Workflow n8n yang menghubungkan webhook, AI agent, dan notifikasi operasional.', 2025, true, true, 0),
    ('Knowledge Agent', 'AI', 'Agent yang mengambil konteks dari knowledge base dan mengembalikan jawaban terstruktur.', 2025, true, true, 1)
) as seed(title, category, description, year, is_featured, is_visible, sort_order)
where not exists (select 1 from public.projects);

-- `title` is the single Hero headline field. The legacy tagline column is removed
-- after seeding so both fresh and existing installations end with the same schema.
alter table public.personals drop column if exists tagline;
drop table if exists public.journeys;
