"use client";

import { FormEvent, useState } from "react";
import { MessageCircle, Send, Sparkles, X } from "lucide-react";

type Message = { role: "user" | "assistant"; content: string };
const starter: Message = { role: "assistant", content: "Halo, saya bisa bantu menjawab pertanyaan singkat tentang Djibril, karya, skill, dan pengalamannya." };

export default function PortfolioAssistant() {
  const [open, setOpen] = useState(false); const [input, setInput] = useState(""); const [messages, setMessages] = useState<Message[]>([starter]); const [pending, setPending] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const question = input.trim(); if (!question || pending) return; const next = [...messages, { role: "user" as const, content: question }]; setMessages(next); setInput(""); setPending(true); try { const response = await fetch("/api/portfolio-chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ messages: next }) }); const payload = await response.json() as { answer?: string; error?: string }; if (!response.ok || !payload.answer) throw new Error(payload.error || "Asisten sedang tidak tersedia."); setMessages((current) => [...current, { role: "assistant", content: payload.answer! }]); } catch (error) { setMessages((current) => [...current, { role: "assistant", content: error instanceof Error ? error.message : "Asisten sedang tidak tersedia." }]); } finally { setPending(false); } }
  return <div className="fixed bottom-4 right-4 z-40 sm:bottom-6 sm:right-6">{open && <section className="mb-3 flex h-[min(31rem,calc(100dvh-7rem))] w-[calc(100vw-2rem)] max-w-sm flex-col overflow-hidden rounded-[12px] border border-[#FF3D00]/55 bg-[#0D0F0E] shadow-[0_20px_60px_rgba(0,0,0,0.52)]"><header className="flex items-center justify-between border-b border-white/[0.12] bg-[#121514] px-4 py-3"><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-[#FF6B35]" /><div><p className="font-['Syne'] text-sm font-bold text-white">Tanya DJ</p><p className="font-mono text-[9px] uppercase tracking-[0.12em] text-white/45">Portfolio assistant</p></div></div><button type="button" onClick={() => setOpen(false)} aria-label="Tutup asisten" className="p-1.5 text-white/55 transition hover:text-[#FF6B35]"><X className="h-4 w-4" /></button></header><div className="flex-1 space-y-3 overflow-y-auto p-4">{messages.map((message, index) => <div key={`${message.role}-${index}`} className={`max-w-[88%] border px-3 py-2.5 text-sm leading-6 ${message.role === "user" ? "ml-auto border-[#FF3D00]/50 bg-[#FF3D00] text-white" : "border-white/[0.12] bg-white/[0.04] text-white/75"}`}>{message.content}</div>)}{pending && <div className="w-fit border border-white/[0.12] bg-white/[0.04] px-3 py-2 text-xs text-white/55">Menjawab...</div>}</div><form onSubmit={submit} className="flex gap-2 border-t border-white/[0.12] p-3"><input value={input} onChange={(event) => setInput(event.target.value)} maxLength={600} placeholder="Tanya tentang DJ..." className="h-10 min-w-0 flex-1 border border-white/[0.14] bg-black/20 px-3 text-sm text-white outline-none placeholder:text-white/30 focus:border-[#FF3D00]" /><button type="submit" disabled={pending || !input.trim()} aria-label="Kirim pertanyaan" className="inline-flex h-10 w-10 shrink-0 items-center justify-center bg-[#FF3D00] text-white transition hover:bg-[#FF6B35] disabled:opacity-40"><Send className="h-4 w-4" /></button></form></section>}<button type="button" onClick={() => setOpen((value) => !value)} aria-label="Buka tanya jawab portfolio" className="inline-flex h-12 items-center gap-2 rounded-[10px] border border-[#FF6B35]/70 bg-[#121514] px-4 text-sm font-bold text-white shadow-[0_12px_32px_rgba(0,0,0,0.35)] transition hover:-translate-y-0.5 hover:bg-[#FF3D00]"><MessageCircle className="h-4 w-4" />Tanya DJ</button></div>;
}
